# Generated by Django 3.2.8 on 2021-10-12 09:34

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=9, prefix='', primary_key=True, serialize=False)),
                ('poster', models.ImageField(upload_to='')),
                ('name', models.TextField(max_length=100)),
                ('date', models.DateTimeField(null=True)),
                ('place', models.TextField(blank=True, max_length=100, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['added'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=9, prefix='', primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=100)),
                ('desc', models.TextField(max_length=100)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('video', embed_video.fields.EmbedVideoField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='VGSDo.category')),
            ],
            options={
                'ordering': ['added'],
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=9, prefix='', primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to='')),
                ('desc', models.TextField(max_length=200)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='VGSDo.category')),
            ],
            options={
                'ordering': ['added'],
            },
        ),
    ]
