# Generated by Django 3.2.8 on 2021-10-12 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VGSDo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='category',
        ),
    ]
